[package]
name = "mandel-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7.0"
num_cpus = "1.13.1"
image = "0.24.1"

[profile.release]
strip = true
lto = true
